theme: jekyll-theme-minimal
logo: https://upload.wikimedia.org/wikipedia/commons/2/2f/Southern_Yellowjacket_%28Vespula_squamosa%29_%287225863346%29.jpg
title: "Bioinformatics Classwork with PrettyPolistes"
